#!/usr/bin/env bash
set -euo pipefail

# Create the AnalyticsHub database, role, and schema.
# Passwords are never printed. If ANALYTICS_DB_PASSWORD is empty, a strong
# password is generated and written to a root-only credential file.

PG_SUPERUSER="${PG_SUPERUSER:-postgres}"
DB_NAME="${DB_NAME:-analytics}"
DB_USER="${DB_USER:-analytic}"
DB_SCHEMA="${DB_SCHEMA:-analytics}"
ANALYTICS_DB_PASSWORD="${ANALYTICS_DB_PASSWORD:-}"
CREDENTIAL_FILE="${CREDENTIAL_FILE:-/root/analyticshub-db-credentials.txt}"

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Please run as root: sudo $0" >&2
    exit 1
  fi
}

random_password() {
  openssl rand -base64 36 | tr -d '=+/ ' | cut -c1-32
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

psql_as_admin() {
  if [[ "$(id -un)" == "$PG_SUPERUSER" ]]; then
    psql -v ON_ERROR_STOP=1 "$@"
  elif command_exists sudo; then
    sudo -u "$PG_SUPERUSER" psql -v ON_ERROR_STOP=1 "$@"
  else
    su - "$PG_SUPERUSER" -c "psql -v ON_ERROR_STOP=1 $*"
  fi
}

ensure_role() {
  local escaped
  escaped="$(sql_escape "$ANALYTICS_DB_PASSWORD")"
  psql_as_admin postgres <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${escaped}';
  ELSE
    ALTER ROLE ${DB_USER} LOGIN PASSWORD '${escaped}';
  END IF;
END
\$\$;
SQL
}

ensure_database() {
  psql_as_admin postgres <<SQL
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER} ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}')\gexec
ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};
REVOKE CONNECT ON DATABASE ${DB_NAME} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER};
SQL
}

ensure_schema() {
  psql_as_admin "$DB_NAME" <<SQL
CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA} AUTHORIZATION ${DB_USER};
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
GRANT USAGE, CREATE ON SCHEMA ${DB_SCHEMA} TO ${DB_USER};
SQL
}

write_credentials_file() {
  install -m 600 -o root -g root /dev/null "$CREDENTIAL_FILE"
  cat >"$CREDENTIAL_FILE" <<EOF
# Generated by ops/server/create-analytics-database.sh
# Keep this file root-only. Do not commit it.

ANALYTICS_DB_USER=${DB_USER}
ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD}
ANALYTICS_DATABASE=${DB_NAME}
ANALYTICS_SCHEMA=${DB_SCHEMA}
EOF
  chmod 600 "$CREDENTIAL_FILE"
}

require_root
ANALYTICS_DB_PASSWORD="${ANALYTICS_DB_PASSWORD:-$(random_password)}"

ensure_role
ensure_database
ensure_schema
write_credentials_file

echo "AnalyticsHub database is ready."
echo "Credentials written to root-only file: $CREDENTIAL_FILE"
