#!/usr/bin/env bash
set -euo pipefail

# Create the AnalyticsHub database, role, and schema.
#
# This script owns initial database provisioning only. Once the role exists,
# its password and all secret files are left untouched. Password changes must
# go through rotate-analytics-secrets.sh so PostgreSQL and the app env are
# updated as one operation.

PG_SUPERUSER="${PG_SUPERUSER:-postgres}"
DB_NAME="${DB_NAME:-analytics}"
DB_USER="${DB_USER:-analytic}"
DB_SCHEMA="${DB_SCHEMA:-analytics}"
ANALYTICS_DB_PASSWORD="${ANALYTICS_DB_PASSWORD:-}"
CREDENTIAL_FILE="${CREDENTIAL_FILE:-/root/analyticshub-db-credentials.txt}"
APP_NAME="${APP_NAME:-analyticshub}"
ENV_FILE="${ENV_FILE:-/etc/${APP_NAME}/${APP_NAME}.env}"

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Please run as root: sudo $0" >&2
    exit 1
  fi
}

random_password() {
  openssl rand -base64 36 | tr -d '=+/ ' | cut -c1-32
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

validate_identifier() {
  local name="$1"
  local value="$2"
  if [[ ! "$value" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "$name must be a PostgreSQL identifier containing only letters, digits, and underscores: $value" >&2
    exit 1
  fi
}

psql_as_admin() {
  if [[ "$(id -un)" == "$PG_SUPERUSER" ]]; then
    psql -v ON_ERROR_STOP=1 "$@"
  elif command_exists sudo; then
    sudo -u "$PG_SUPERUSER" psql -v ON_ERROR_STOP=1 "$@"
  else
    su - "$PG_SUPERUSER" -c "psql -v ON_ERROR_STOP=1 $*"
  fi
}

role_exists() {
  local escaped result
  escaped="$(sql_escape "$DB_USER")"
  result="$(psql_as_admin postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname = '${escaped}';")"
  [[ "${result//[[:space:]]/}" == "1" ]]
}

get_file_value() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 1
  awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' "$file"
}

is_usable_password() {
  local value="$1"
  [[ -n "$value" && "$value" != replace-with-* ]]
}

resolve_initial_password() {
  local value
  if is_usable_password "$ANALYTICS_DB_PASSWORD"; then
    return
  fi

  value="$(get_file_value "$ENV_FILE" DB_PASSWORD || true)"
  if is_usable_password "$value"; then
    ANALYTICS_DB_PASSWORD="$value"
    return
  fi

  value="$(get_file_value "$CREDENTIAL_FILE" ANALYTICS_DB_PASSWORD || true)"
  if is_usable_password "$value"; then
    ANALYTICS_DB_PASSWORD="$value"
    return
  fi

  ANALYTICS_DB_PASSWORD="$(random_password)"
}

create_role() {
  local escaped
  escaped="$(sql_escape "$ANALYTICS_DB_PASSWORD")"
  psql_as_admin postgres <<SQL
CREATE ROLE ${DB_USER} LOGIN PASSWORD '${escaped}';
SQL
}

ensure_database() {
  psql_as_admin postgres <<SQL
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER} ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}')\gexec
ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};
REVOKE CONNECT ON DATABASE ${DB_NAME} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER};
SQL
}

ensure_schema() {
  psql_as_admin "$DB_NAME" <<SQL
CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA} AUTHORIZATION ${DB_USER};
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
GRANT USAGE, CREATE ON SCHEMA ${DB_SCHEMA} TO ${DB_USER};
SQL
}

write_credentials_file() {
  install -m 600 -o root -g root /dev/null "$CREDENTIAL_FILE"
  cat >"$CREDENTIAL_FILE" <<EOF
# Generated by ops/server/create-analytics-database.sh
# Keep this file root-only. Do not commit it.

ANALYTICS_DB_USER=${DB_USER}
ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD}
ANALYTICS_DATABASE=${DB_NAME}
ANALYTICS_SCHEMA=${DB_SCHEMA}
EOF
  chmod 600 "$CREDENTIAL_FILE"
}

main() {
  local role_created=false

  require_root
  validate_identifier PG_SUPERUSER "$PG_SUPERUSER"
  validate_identifier DB_NAME "$DB_NAME"
  validate_identifier DB_USER "$DB_USER"
  validate_identifier DB_SCHEMA "$DB_SCHEMA"

  if role_exists; then
    echo "AnalyticsHub database role already exists; password and secret files were kept unchanged."
  else
    resolve_initial_password
    create_role
    write_credentials_file
    role_created=true
  fi

  ensure_database
  ensure_schema

  echo "AnalyticsHub database is ready."
  if [[ "$role_created" == "true" ]]; then
    echo "Initial credentials written to root-only file: $CREDENTIAL_FILE"
  else
    echo "Use ops/analyticshub rotate-secrets for intentional password changes."
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
