#!/usr/bin/env bash
set -euo pipefail

# Rotate AnalyticsHub database password and admin token.
# Secrets are written only to root-owned env/credential files and are not
# printed to stdout.

PG_SUPERUSER="${PG_SUPERUSER:-postgres}"
APP_NAME="${APP_NAME:-analyticshub}"
ENV_FILE="${ENV_FILE:-/etc/${APP_NAME}/${APP_NAME}.env}"
CREDENTIAL_FILE="${CREDENTIAL_FILE:-/root/analyticshub-db-credentials.txt}"
RESTART_SERVICE="${RESTART_SERVICE:-true}"
ROTATE_DB_PASSWORD="${ROTATE_DB_PASSWORD:-true}"
ROTATE_ADMIN_TOKEN="${ROTATE_ADMIN_TOKEN:-true}"
ROTATE_2FA_SECRET="${ROTATE_2FA_SECRET:-false}"

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Please run as root: sudo $0" >&2
    exit 1
  fi
}

require_file() {
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "Required file missing: $file" >&2
    exit 1
  fi
}

random_password() {
  openssl rand -base64 48 | tr -d '=+/ ' | cut -c1-40
}

random_token() {
  openssl rand -hex 32
}

random_totp_secret() {
  openssl rand -base64 20 | tr -d '=+/ ' | cut -c1-32
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

psql_as_admin() {
  if [[ "$(id -un)" == "$PG_SUPERUSER" ]]; then
    psql -v ON_ERROR_STOP=1 "$@"
  elif command_exists sudo; then
    sudo -u "$PG_SUPERUSER" psql -v ON_ERROR_STOP=1 "$@"
  else
    su - "$PG_SUPERUSER" -c "psql -v ON_ERROR_STOP=1 $*"
  fi
}

get_env_value() {
  local key="$1"
  awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' "$ENV_FILE"
}

set_env_value() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

write_credentials_file() {
  local db_user="$1"
  local db_password="$2"
  local db_name="$3"
  local db_schema="$4"
  install -m 600 -o root -g root /dev/null "$CREDENTIAL_FILE"
  cat >"$CREDENTIAL_FILE" <<EOF
# Generated by ops/server/rotate-analytics-secrets.sh
# Keep this file root-only. Do not commit it.

ANALYTICS_DB_USER=${db_user}
ANALYTICS_DB_PASSWORD=${db_password}
ANALYTICS_DATABASE=${db_name}
ANALYTICS_SCHEMA=${db_schema}
EOF
  chmod 600 "$CREDENTIAL_FILE"
}

check_health() {
  local port
  port="$(get_env_value SERVER_PORT)"
  curl -fsS "http://127.0.0.1:${port:-3001}/api/health" >/dev/null
}

require_root
require_file "$ENV_FILE"

db_user="$(get_env_value DB_USER)"
db_name="$(get_env_value DB_NAME)"
db_schema="$(get_env_value DB_SCHEMA)"
db_password="$(get_env_value DB_PASSWORD)"

if [[ -z "$db_user" || -z "$db_name" || -z "$db_schema" ]]; then
  echo "DB_USER, DB_NAME, and DB_SCHEMA must be configured in $ENV_FILE." >&2
  exit 1
fi

if [[ "$ROTATE_DB_PASSWORD" == "true" ]]; then
  db_password="$(random_password)"
  psql_as_admin postgres -c "ALTER ROLE ${db_user} PASSWORD '$(sql_escape "$db_password")';"
  set_env_value DB_PASSWORD "$db_password"
  write_credentials_file "$db_user" "$db_password" "$db_name" "$db_schema"
fi

if [[ "$ROTATE_ADMIN_TOKEN" == "true" ]]; then
  set_env_value ADMIN_TOKEN "$(random_token)"
fi

if [[ "$ROTATE_2FA_SECRET" == "true" ]]; then
  set_env_value APP_SECURITY_2FA_SECRET "$(random_totp_secret)"
fi

chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

if [[ "$RESTART_SERVICE" == "true" ]]; then
  systemctl restart "$APP_NAME"
  for _ in {1..12}; do
    if check_health; then
      echo "AnalyticsHub secrets rotated. Service restarted and health check passed."
      exit 0
    fi
    sleep 3
  done
  echo "Secrets rotated, but health check did not pass in time." >&2
  exit 1
fi

echo "AnalyticsHub secrets rotated. Service restart skipped by RESTART_SERVICE=false."
